// Public visual deck. Presenter notes are not included.
window.SLIDES = [
  {
    "chapter": "Opening",
    "layout": "editorial cover",
    "title": "Agent orchestration: from one chat to a system of work",
    "html": "\n      <p class=\"context\">VS Code + GitHub · September 2026</p>\n      <div class=\"cover-composition\">\n        <h1>Agent<br><span>orchestration.</span></h1>\n        <p class=\"cover-deck\">From one chat<br>to a system of work.</p>\n        <svg class=\"cover-branches\" viewBox=\"0 0 1000 265\" role=\"img\" aria-label=\"One task branches into research, implementation, and verification, then joins at a pull request\">\n          <path class=\"ink-base\" d=\"M40 145H180C250 145 240 50 310 50H665C745 50 740 145 810 145H970\"/>\n          <path class=\"ink-base\" d=\"M180 145H810\"/>\n          <path class=\"ink-base\" d=\"M180 145C250 145 240 240 310 240H665C745 240 740 145 810 145\"/>\n          <path class=\"ink-path blue-ink\" pathLength=\"1\" d=\"M40 145H180C250 145 240 50 310 50H665C745 50 740 145 810 145H970\"/>\n          <path class=\"ink-path violet-ink\" pathLength=\"1\" style=\"--delay:.2s\" d=\"M180 145H810\"/>\n          <path class=\"ink-path green-ink\" pathLength=\"1\" style=\"--delay:.4s\" d=\"M180 145C250 145 240 240 310 240H665C745 240 740 145 810 145\"/>\n          <g class=\"branch-nodes\">\n            <circle cx=\"40\" cy=\"145\" r=\"10\"/><circle cx=\"410\" cy=\"50\" r=\"10\"/>\n            <circle cx=\"530\" cy=\"145\" r=\"10\"/><circle cx=\"410\" cy=\"240\" r=\"10\"/>\n            <circle class=\"arrival\" style=\"--delay:1.8s\" cx=\"970\" cy=\"145\" r=\"14\"/>\n          </g>\n          <g class=\"branch-labels\">\n            <text x=\"20\" y=\"111\">TASK</text><text x=\"410\" y=\"27\">RESEARCH</text>\n            <text x=\"530\" y=\"121\">IMPLEMENT</text><text x=\"410\" y=\"214\">VERIFY</text>\n            <text x=\"902\" y=\"111\">PULL REQUEST</text>\n          </g>\n        </svg>\n      </div>\n      <div class=\"editorial-foot\"><span>Sessions. Models. Pull requests. Recurring work.</span><span>Human decisions stay in the loop.</span></div>\n    ",
    "kicker": ""
  },
  {
    "chapter": "Opening",
    "layout": "editorial timeline",
    "title": "Delegate independent work. Spend attention on decisions.",
    "html": "\n      <p class=\"context\">Parallel work, selective attention</p>\n      <h2>Delegate independent work.<br>Spend attention on <em>decisions.</em></h2>\n      <div class=\"work-score\" role=\"img\" aria-label=\"Illustrative timeline. Independent tasks run in parallel. The developer decides scope, answers a blocker, and reviews results. No timing or speedup is measured.\">\n        <div class=\"score-ruler\"><span>Work begins</span><span>Work continues</span><span>Results need review</span></div>\n        <div class=\"score-row human-row\"><b>You</b><div class=\"score-track\">\n          <span class=\"decision start\">Set scope</span><span class=\"decision middle arrival\" style=\"--delay:1s\">Answer</span><span class=\"decision end arrival\" style=\"--delay:2s\">Review</span>\n        </div></div>\n        <div class=\"score-row\"><b>Research</b><div class=\"score-track\">\n          <span class=\"work-bar blue-bar\" style=\"--start:2%;--span:42%;--delay:.1s\">Find existing patterns</span><span class=\"score-result\" style=\"left:47%\">Findings ready</span>\n        </div></div>\n        <div class=\"score-row\"><b>Implement</b><div class=\"score-track\">\n          <span class=\"work-bar violet-bar\" style=\"--start:8%;--span:35%;--delay:.3s\">Change the API</span><span class=\"work-bar violet-bar\" style=\"--start:53%;--span:28%;--delay:1.3s\">Continue</span>\n          <span class=\"blocker-pin\" style=\"left:47%\" aria-label=\"Needs a decision\">!</span>\n        </div></div>\n        <div class=\"score-row\"><b>Investigate</b><div class=\"score-track\">\n          <span class=\"work-bar green-bar\" style=\"--start:15%;--span:54%;--delay:.5s\">Check compatibility risks</span><span class=\"score-result\" style=\"left:72%\">Report ready</span>\n        </div></div>\n      </div>\n      <div class=\"editorial-foot\"><span>Parallelism still needs clear ownership and integration.</span><span>Illustrative sequence, not a speedup claim.</span></div>\n    ",
    "kicker": ""
  },
  {
    "chapter": "Opening",
    "layout": "editorial attention",
    "title": "The Agents window shows what is running and what needs you.",
    "html": "\n      <p class=\"context\">Agents window · session state</p>\n      <h2>The Agents window shows what is running<br>and what <em>needs you.</em></h2>\n      <div class=\"attention-composition\">\n        <div class=\"attention-list\" aria-label=\"Illustrative sessions, not a product screenshot\">\n          <div class=\"attention-row\"><i class=\"status-dot blue-dot\"></i><div><strong>Build the change</strong><small>Worktree · running</small></div><span class=\"mini-activity\" aria-hidden=\"true\"></span></div>\n          <div class=\"attention-row attention-needed arrival\" style=\"--delay:.8s\"><i class=\"status-dot amber-dot\"></i><div><strong>Check compatibility</strong><small>Waiting for your answer</small></div><span class=\"attention-mark\">?</span></div>\n          <div class=\"attention-row\"><i class=\"status-dot green-dot\"></i><div><strong>Research the dependency</strong><small>Completed · unread findings</small></div><span class=\"codicon codicon-check\" aria-hidden=\"true\"></span></div>\n          <div class=\"attention-row\"><i class=\"status-dot violet-dot\"></i><div><strong>Review the pull request</strong><small>Required check failed</small></div><span class=\"codicon codicon-git-pull-request\" aria-hidden=\"true\"></span></div>\n        </div>\n        <div class=\"attention-explanation\">\n          <span class=\"editorial-label\">Select a session</span>\n          <p class=\"big-annotation\">Its workspace.<br>Its changes.<br>Its conversation.</p>\n          <div class=\"annotation-rule\"></div>\n          <p>The active session also owns the terminal, tasks, and browser context.</p>\n        </div>\n      </div>\n      <div class=\"editorial-foot\"><span>Follow the state of the work, not just the latest message.</span><span>Illustrative session view</span></div>\n    ",
    "kicker": ""
  },
  {
    "chapter": "Research before code",
    "layout": "section",
    "title": "Ask before you plan.",
    "html": "\n      <div class=\"transition-statement\">\n        <div class=\"divider-line reveal\"></div>\n        <p class=\"context reveal\">Part 1 · Research before code</p>\n        <h2 class=\"reveal\">Ask before you plan.</h2>\n      </div>\n    ",
    "kicker": ""
  },
  {
    "chapter": "Research before code",
    "layout": "editorial conversation",
    "title": "Side chat explores questions. Plan feedback steers changes.",
    "html": "\n      <p class=\"context\">Human + agent · illustrative API change</p>\n      <h2>Side chat explores questions.<br>Plan feedback <em>steers changes.</em></h2>\n      <div class=\"conversation-map\">\n        <div class=\"main-thread\">\n          <div class=\"thread-event\"><span class=\"thread-node\"></span><small>RESEARCH</small><strong>Find the API conventions and existing callers.</strong></div>\n          <div class=\"thread-event\"><span class=\"thread-node\"></span><small>ASK QUESTIONS</small><strong>Must existing clients keep the same response?</strong></div>\n          <div class=\"plan-paper\">\n            <span class=\"paper-label\">Review Plan</span>\n            <p>Add optional pagination.<br>Preserve requests without pagination.</p>\n            <div class=\"anchored-line\">Add compatibility tests.</div>\n          </div>\n          <div class=\"feedback-return arrival\" style=\"--delay:1.8s\"><span class=\"codicon codicon-refresh\" aria-hidden=\"true\"></span> Revise plan. Do not implement yet.</div>\n        </div>\n        <div class=\"side-thread\">\n          <div class=\"side-question\">\n            <code>/btw</code>\n            <strong>Would a cursor avoid duplicates when the list changes?</strong>\n            <p>Explore the trade-off using the source conversation's context.</p>\n            <small>Separate transcript. Shared workspace.</small>\n          </div>\n          <div class=\"margin-comment arrival\" style=\"--delay:1s\">\n            <span class=\"editorial-label\">Comment on the plan</span>\n            <p>\"Add a test for an insertion between page requests.\"</p>\n            <span class=\"control-label\">Submit Feedback <span aria-hidden=\"true\">&#8599;</span></span>\n          </div>\n        </div>\n      </div>\n      <div class=\"editorial-foot\"><span>Bring the conclusion back explicitly.</span><span>Pending feedback blocks approval.</span></div>\n    ",
    "kicker": ""
  },
  {
    "chapter": "Research before code",
    "layout": "editorial artifacts",
    "title": "Make the plan reviewable.",
    "html": "\n      <p class=\"context\">Same proposal, different decisions</p>\n      <h2>Make the plan <em>reviewable.</em></h2>\n      <div class=\"artifact-gallery\">\n        <figure class=\"artifact-sheet architecture-sheet\">\n          <figcaption><span>Architecture</span><strong>Where does the cursor live?</strong></figcaption>\n          <svg viewBox=\"0 0 300 220\" role=\"img\" aria-label=\"Illustrative pagination architecture: client requests API, API uses ordered query to read database, and returns items plus a cursor\">\n            <rect x=\"18\" y=\"15\" width=\"110\" height=\"47\" rx=\"5\"/><text x=\"73\" y=\"44\">Client</text>\n            <rect x=\"170\" y=\"15\" width=\"110\" height=\"47\" rx=\"5\"/><text x=\"225\" y=\"44\">API</text>\n            <path d=\"M128 37H165M160 32L165 37L160 42\"/>\n            <path class=\"artifact-edge\" d=\"M225 62V133M220 128L225 133L230 128\"/>\n            <text class=\"tiny\" x=\"225\" y=\"95\">ordered query</text>\n            <rect x=\"170\" y=\"138\" width=\"110\" height=\"47\" rx=\"5\"/><text x=\"225\" y=\"168\">Database</text>\n            <path d=\"M170 52H147V160H73V68M68 73L73 68L78 73\"/>\n            <text class=\"tiny\" x=\"87\" y=\"204\">items + next cursor</text>\n          </svg>\n          <p>Review dependencies and data boundaries.</p>\n        </figure>\n        <figure class=\"artifact-sheet prototype-sheet\">\n          <figcaption><span>UX prototype</span><strong>What does the user see?</strong></figcaption>\n          <div class=\"mini-prototype\" role=\"img\" aria-label=\"Illustrative product list with two rows and a Load more control\">\n            <div class=\"prototype-title\">Products <span>Browse</span></div>\n            <div class=\"prototype-item\"><i></i><div>Mechanical keyboard<small>In stock</small></div></div>\n            <div class=\"prototype-item\"><i></i><div>USB-C dock<small>In stock</small></div></div>\n            <div class=\"prototype-button\">Load more <span aria-hidden=\"true\">&#8595;</span></div>\n          </div>\n          <p>Review behavior before implementation.</p>\n        </figure>\n        <figure class=\"artifact-sheet risk-sheet\">\n          <figcaption><span>Risk analysis</span><strong>What could break?</strong></figcaption>\n          <table><thead><tr><th>Risk</th><th>Check</th></tr></thead><tbody>\n            <tr><td>Rows repeat</td><td>Insert between page requests</td></tr>\n            <tr><td>Old callers break</td><td>Omit pagination parameters</td></tr>\n            <tr><td>Order changes</td><td>Test equal sort values</td></tr>\n          </tbody></table>\n          <p>Review failure modes and test evidence.</p>\n        </figure>\n      </div>\n      <div class=\"editorial-foot\"><span>Ask the agent for an artifact people can review.</span><span>Illustrative artifacts, not a native visual Plan mode.</span></div>\n    ",
    "kicker": ""
  },
  {
    "chapter": "Parallel sessions",
    "layout": "section",
    "title": "Parallel work needs ownership",
    "html": "\n      <div class=\"transition-statement\">\n        <div class=\"divider-line reveal\"></div>\n        <p class=\"context reveal\">Part 2 · Parallel sessions</p>\n        <h2 class=\"reveal\">Parallel work needs ownership.</h2>\n      </div>\n    ",
    "kicker": ""
  },
  {
    "chapter": "Parallel sessions",
    "layout": "editorial delegation",
    "title": "Session orchestration lets one session start and steer others.",
    "html": "\n      <p class=\"context\">Session orchestration · built into VS Code</p>\n      <h2>Session orchestration lets one session<br>start and <em>steer others.</em></h2>\n      <div class=\"delegation-composition\">\n        <div class=\"delegation-request\">\n          <span class=\"editorial-label\">Your request</span>\n          <blockquote>Have another session investigate compatibility. Keep implementation in its own worktree.</blockquote>\n          <p>Give each task an objective, a workspace, and a result to return.</p>\n          <div class=\"delegated-work arrival\" style=\"--delay:.4s\">\n            <span><i class=\"status-dot green-dot\"></i><b>Compatibility research</b><small>Findings and file references</small></span>\n            <span><i class=\"status-dot violet-dot\"></i><b>Implementation</b><small>Branch and code changes</small></span>\n          </div>\n        </div>\n        <div class=\"session-operations\">\n          <div><span class=\"codicon codicon-list-tree\" aria-hidden=\"true\"></span><strong>Find the work</strong><p>List sessions, status, workspaces, and changes.</p></div>\n          <div class=\"arrival\" style=\"--delay:.5s\"><span class=\"codicon codicon-add\" aria-hidden=\"true\"></span><strong>Start a task</strong><p>Create a session, or a chat within a session.</p></div>\n          <div class=\"arrival\" style=\"--delay:1s\"><span class=\"codicon codicon-comment-discussion\" aria-hidden=\"true\"></span><strong>Read and follow up</strong><p>Read recent context. Send a targeted message.</p><small class=\"confirmation-label\">Cross-session messages require your confirmation.</small></div>\n        </div>\n      </div>\n      <div class=\"editorial-foot\"><span>A new chat can share a workspace. A new session can have its own.</span><span>Separate conversations do not guarantee separate files.</span></div>\n    ",
    "kicker": ""
  },
  {
    "chapter": "Parallel sessions",
    "layout": "editorial pr-stack",
    "title": "Parallel sessions can turn a plan into stacked PRs.",
    "html": "\n      <p class=\"context\">Session orchestration + GitHub stacked pull requests</p>\n      <h2>Parallel sessions can turn a plan<br>into <em>stacked PRs.</em></h2>\n      <div class=\"stacked-work-composition\">\n        <div class=\"stacked-work-plan\">\n          <span class=\"editorial-label\">One agreed plan</span>\n          <h3>Add pagination<br>to the product list.</h3>\n          <p>Agree on the cursor contract.<br>Split API and UI work into sessions.</p>\n          <div class=\"parallel-task\"><span class=\"status-dot blue-dot\"></span><div><b>API session</b><small>Endpoint + cursor tests</small></div></div>\n          <div class=\"parallel-task\"><span class=\"status-dot violet-dot\"></span><div><b>UI session</b><small>Load more + recovery states</small></div></div>\n        </div>\n        <div class=\"stacked-pr-layers\">\n          <span class=\"editorial-label\">Separate branches · focused diffs</span>\n          <div class=\"stacked-pr-layer ui-layer arrival\" style=\"--delay:.6s\"><span class=\"codicon codicon-git-pull-request\" aria-hidden=\"true\"></span><div><b>UI pull request</b><p>Load and display the next page.</p><code>ui/pagination → api/pagination</code></div><span class=\"stack-review\">review + checks</span></div>\n          <div class=\"stack-dependency\"><span aria-hidden=\"true\">↓</span> Targets the API branch below it.</div>\n          <div class=\"stacked-pr-layer api-layer arrival\" style=\"--delay:1s\"><span class=\"codicon codicon-git-pull-request\" aria-hidden=\"true\"></span><div><b>API pull request</b><p>Return results and a next cursor.</p><code>api/pagination → main</code></div><span class=\"stack-review\">review + checks</span></div>\n          <div class=\"stack-trunk\"><span class=\"codicon codicon-git-branch\" aria-hidden=\"true\"></span><code>main</code><span>Its rules apply to every layer.</span></div>\n        </div>\n      </div>\n      <div class=\"editorial-foot\"><span>Work in parallel against the contract. Rebase as dependencies change.</span><span>Review each layer. Merge ready layers together.</span></div>\n    ",
    "kicker": ""
  },
  {
    "chapter": "Parallel sessions",
    "layout": "editorial collision",
    "title": "Separate chats still share the machine.",
    "html": "\n      <p class=\"context\">Illustrative failures · two agents in one folder</p>\n      <h2>Separate chats still<br><em>share the machine.</em></h2>\n      <div class=\"collision-composition\">\n        <div class=\"collision-file\">\n          <span class=\"editorial-label\">Same file, different assumptions</span>\n          <div class=\"file-tab\"><span class=\"codicon codicon-file-code\" aria-hidden=\"true\"></span> src/api.ts</div>\n          <div class=\"edit-fragment\"><span>Agent A</span><code>return { items, cursor };</code></div>\n          <div class=\"edit-fragment conflicting-edit arrival\" style=\"--delay:.7s\"><span>Agent B</span><code>return items;</code></div>\n          <p>One edit changes the code the other agent is using.</p>\n        </div>\n        <div class=\"collision-terminal\">\n          <span class=\"editorial-label\">Different process, same port</span>\n          <div class=\"terminal-output\"><span class=\"terminal-actor\">Agent A</span><code>$ npm run dev</code><strong class=\"green\">Listening on :3000</strong><span class=\"terminal-actor\">Agent B</span><code>$ npm run dev</code><strong class=\"red arrival\" style=\"--delay:1s\">EADDRINUSE<br><small>address already in use :3000</small></strong></div>\n        </div>\n        <div class=\"shared-pressure\"><span class=\"codicon codicon-server-process\" aria-hidden=\"true\"></span><p>Builds, tests, and watchers also compete for <strong>CPU and memory.</strong></p></div>\n      </div>\n      <div class=\"editorial-foot\"><span>Code conflicts and resource conflicts need different fixes.</span><span>Access to files, networks, and credentials is another boundary.</span></div>\n    ",
    "kicker": ""
  },
  {
    "chapter": "Parallel sessions",
    "layout": "editorial worktrees",
    "title": "Worktrees separate edits. The machine is still shared.",
    "html": "\n      <p class=\"context\">Code isolation</p>\n      <h2>Worktrees separate edits.<br>The machine is <em>still shared.</em></h2>\n      <div class=\"worktree-machine\">\n        <span class=\"machine-label\"><span class=\"codicon codicon-device-desktop\" aria-hidden=\"true\"></span> ONE HOST</span>\n        <div class=\"worktree-pair\">\n          <div class=\"checkout-boundary\"><span class=\"editorial-label\">Worktree A</span><h3><span class=\"codicon codicon-git-branch\" aria-hidden=\"true\"></span> feat/pagination</h3><div class=\"checkout-file\"><code>src/api.ts</code><span class=\"diff-add\">+ items + cursor</span></div><p>Own checkout, index, and changes</p></div>\n          <div class=\"checkout-boundary alternate-checkout\"><span class=\"editorial-label\">Worktree B</span><h3><span class=\"codicon codicon-git-branch\" aria-hidden=\"true\"></span> fix/retry</h3><div class=\"checkout-file\"><code>src/api.ts</code><span class=\"diff-add\">+ retry on timeout</span></div><p>Own checkout, index, and changes</p></div>\n        </div>\n        <div class=\"machine-bus\"><span>Shared CPU + memory</span><span>Shared ports + processes</span><span>No added security boundary</span></div>\n      </div>\n      <div class=\"editorial-foot\"><span>New Worktree starts from a committed base branch.</span><span>Uncommitted changes and ignored files do not appear automatically.</span></div>\n    ",
    "kicker": ""
  },
  {
    "chapter": "Parallel sessions",
    "layout": "editorial containers",
    "title": "Dev Containers put the toolchain with the agent.",
    "html": "\n      <p class=\"context\">VS Code 1.139 · remote Dev Container sessions</p>\n      <h2>Dev Containers put the<br><em>toolchain with the agent.</em></h2>\n      <div class=\"container-composition\">\n        <div class=\"container-client\"><span class=\"codicon codicon-vscode\" aria-hidden=\"true\"></span><h3>Desktop<br>Agents window</h3><span class=\"control-label\">Use Dev Container</span><p>Local folder, or a folder on SSH, Tunnel, or WSL.</p></div>\n        <div class=\"container-host\">\n          <span class=\"machine-label\">MACHINE WITH THE PROJECT + DOCKER</span>\n          <div class=\"container-interior\">\n            <span class=\"editorial-label\">Project Dev Container</span>\n            <div class=\"container-runtime\"><span class=\"codicon codicon-hubot\" aria-hidden=\"true\"></span><strong>Agent Host</strong></div>\n            <div class=\"container-tools\"><span>Compiler</span><span>Dependencies</span><span>Build + test tools</span></div>\n            <div class=\"mounted-project\"><span class=\"codicon codicon-folder-opened\" aria-hidden=\"true\"></span> Container workspace</div>\n          </div>\n          <code class=\"container-config\">.devcontainer/devcontainer.json</code>\n        </div>\n      </div>\n      <div class=\"editorial-foot\"><span>Docker runs on the machine that holds the project.</span><span>Desktop only. Cannot combine with New Worktree.</span></div>\n    ",
    "kicker": ""
  },
  {
    "chapter": "Parallel sessions",
    "layout": "editorial remote-host",
    "title": "Remote Agent Host runs the build on your DevBox.",
    "html": "\n      <p class=\"context\">Remote Agent Host · your machine, your toolchain</p>\n      <h2>Remote Agent Host runs the build<br>on <em>your DevBox.</em></h2>\n      <div class=\"remote-composition\">\n        <div class=\"supervision-device\"><div class=\"laptop-screen\"><span class=\"codicon codicon-vscode\" aria-hidden=\"true\"></span><strong>VS Code</strong><p>Prompt · steer · approve<br>Review changes</p></div><div class=\"laptop-base\"></div><small>A browser can connect by tunnel, too.</small></div>\n        <div class=\"remote-link\"><span class=\"codicon codicon-lock\" aria-hidden=\"true\"></span><b>Dev Tunnel</b><div class=\"connection-line\"><i class=\"connection-packet\"></i></div><small>SSH is another option.</small></div>\n        <div class=\"devbox-machine\"><span class=\"editorial-label\">Windows DevBox</span><h3>Agent + build tools</h3><div class=\"devbox-slots\"><span>VS Code checkout</span><span>Builds, tests, terminals</span><span>Host CPU + memory</span></div><p>Execution stays beside the code.</p></div>\n      </div>\n      <div class=\"editorial-foot\"><span>The host must remain powered on and reachable.</span><span>Require tunnel authentication.</span></div>\n    ",
    "kicker": ""
  },
  {
    "chapter": "Parallel sessions",
    "layout": "editorial cloud-sandbox",
    "title": "Cloud Sandbox runs the session off your machine.",
    "html": "\n      <p class=\"context\">GitHub-hosted execution · Cloud Sandbox</p>\n      <h2>Cloud Sandbox runs the session<br><em>off your machine.</em></h2>\n      <div class=\"cloud-composition\">\n        <div class=\"cloud-entry\">\n          <span class=\"editorial-label\">Start the session in</span>\n          <h3><span class=\"codicon codicon-vscode\" aria-hidden=\"true\"></span> VS Code</h3>\n          <h3><span class=\"codicon codicon-github\" aria-hidden=\"true\"></span> GitHub Copilot App</h3>\n          <p>Choose Cloud Sandbox for a new session.</p>\n          <div class=\"cli-entry\"><span class=\"editorial-label\">Or Copilot CLI</span><code>copilot --cloud --experimental</code></div>\n        </div>\n        <div class=\"cloud-environment arrival\" style=\"--delay:.45s\">\n          <span class=\"codicon codicon-cloud\" aria-hidden=\"true\"></span><span class=\"editorial-label\">Isolated Linux environment</span>\n          <h3>Session + code + tools</h3><p>GitHub runs the environment.<br>Your laptop does not run the workload.</p>\n        </div>\n      </div>\n      <div class=\"sandbox-lifecycle\" aria-label=\"Running incurs compute and memory charges. Stopping saves a snapshot with storage charges. Deleting removes the environment and snapshot.\">\n        <div><b>Running</b><span>Compute + allocated memory</span></div><span aria-hidden=\"true\">&#8594;</span><div><b>Stopped</b><span>Resume from snapshot. Storage billed.</span></div><span aria-hidden=\"true\">&#8594;</span><div><b>Deleted</b><span>Environment + snapshot removed</span></div>\n      </div>\n      <div class=\"editorial-foot\"><span>Organization policy and a billing owner apply.</span><span>Steer the session from your client. Run the workload on GitHub.</span></div>\n    ",
    "kicker": ""
  },
  {
    "chapter": "Parallel sessions",
    "layout": "editorial protocol",
    "title": "Agent Host Protocol connects clients. The host keeps the session.",
    "html": "\n      <p class=\"context\">Agent Host Protocol · client and host responsibilities</p>\n      <h2>Agent Host Protocol connects clients.<br>The host <em>keeps the session.</em></h2>\n      <div class=\"protocol-composition\">\n        <div class=\"protocol-clients\">\n          <div><span class=\"codicon codicon-device-desktop\" aria-hidden=\"true\"></span><strong>Agents window</strong><small>Observe and control</small></div>\n          <div><span class=\"codicon codicon-browser\" aria-hidden=\"true\"></span><strong>Browser client</strong><small>Attach from another device</small></div>\n        </div>\n        <div class=\"protocol-wire\"><b>AHP</b><span>Commands &#8594;</span><div class=\"connection-line\"><i class=\"connection-packet\"></i></div><span>&#8592; State updates</span><small>Snapshot, then ordered actions</small></div>\n        <div class=\"protocol-host\">\n          <span class=\"editorial-label\">Agent Host · source of truth</span>\n          <h3>Session</h3><div class=\"host-state\"><span>Chats</span><span>Terminals</span><span>Changes</span></div>\n          <p>Agent runtime + workspace tools</p>\n          <div class=\"host-adapters\"><span>Copilot</span><span>Claude</span><span>Codex</span></div>\n        </div>\n      </div>\n      <div class=\"editorial-foot\"><span>Work can continue while the host remains running.</span><span>AHP is communication, not sandboxing or credential management.</span></div>\n    ",
    "kicker": ""
  },
  {
    "chapter": "Parallel sessions",
    "layout": "editorial local-sandbox",
    "title": "The local sandbox limits what commands can reach.",
    "html": "\n      <p class=\"context\">Local sandbox · shared Copilot runtime</p>\n      <h2>The local sandbox limits<br><em>what commands can reach.</em></h2>\n      <div class=\"local-sandbox-composition\">\n        <div class=\"sandbox-command\">\n          <span class=\"editorial-label\">Tool approval</span><h3>May this command run?</h3>\n          <code>npm test</code><p>Approval allows an action.<br>It does not remove an enabled sandbox.</p>\n          <div class=\"policy-inspector\"><span class=\"control-label\">Sandboxing for terminal</span><code>/sandbox-policy</code><span>Inspect the session's effective policy.</span></div>\n        </div>\n        <div class=\"sandbox-boundary\">\n          <span class=\"editorial-label\">Local sandbox · example policy</span>\n          <h3>Shell + child processes</h3>\n          <div class=\"reach-rules\">\n            <div><span class=\"codicon codicon-check green\" aria-hidden=\"true\"></span><strong>Workspace</strong><span>Allowed paths</span></div>\n            <div><span class=\"codicon codicon-error red\" aria-hidden=\"true\"></span><strong>Private files</strong><span>Denied paths</span></div>\n            <div><span class=\"codicon codicon-globe blue\" aria-hidden=\"true\"></span><strong>Outbound network</strong><span>Allow or block</span></div>\n          </div>\n          <p>MXC provides OS containment.<br>Still on this machine. No separate VM.</p>\n        </div>\n      </div>\n      <div class=\"editorial-foot\"><span>Managed policy can require sandboxing and prevent bypass.</span><span>Ordinary tool approval does not widen the sandbox.</span></div>\n    ",
    "kicker": ""
  },
  {
    "chapter": "Autonomy building blocks",
    "layout": "editorial assisted",
    "title": "Assisted permissions judges tool calls before interrupting you.",
    "html": "\n      <p class=\"context\">Assisted permissions · tool-call decisions</p>\n      <h2>Assisted permissions judges tool calls<br><em>before interrupting you.</em></h2>\n      <div class=\"permission-envelope\">\n        <span class=\"editorial-label\">Required approvals and managed policy stay in force</span>\n        <div class=\"assisted-flow\">\n          <div class=\"proposed-tool\"><span class=\"codicon codicon-tools\" aria-hidden=\"true\"></span><strong>Proposed tool call</strong><p>Action + parameters</p></div>\n          <span class=\"decision-connector\" aria-hidden=\"true\">&#8594;</span>\n          <div class=\"risk-judge arrival\" style=\"--delay:.3s\"><span class=\"editorial-label\">LLM risk assessment</span><h3>Approve?</h3><p>Assisted permissions</p></div>\n          <div class=\"judge-outcomes\">\n            <div class=\"judge-approved arrival\" style=\"--delay:.8s\"><span class=\"codicon codicon-check\" aria-hidden=\"true\"></span><strong>Approved</strong><p>Continue without a prompt.</p></div>\n            <div class=\"judge-human arrival\" style=\"--delay:1.2s\"><span class=\"codicon codicon-person\" aria-hidden=\"true\"></span><strong>Not approved</strong><p>Ask you to decide.</p></div>\n          </div>\n        </div>\n        <div class=\"permission-base\"><span class=\"codicon codicon-shield\" aria-hidden=\"true\"></span><p>An enabled sandbox still constrains what the command can reach.</p></div>\n      </div>\n      <div class=\"editorial-foot\"><span>Less approval traffic, with a human fallback.</span><span>The judge is a model. It can make mistakes.</span></div>\n    ",
    "kicker": ""
  },
  {
    "chapter": "Autonomy building blocks",
    "layout": "editorial hydra-routing",
    "title": "Choose HydraFusion. It chooses the model workflow.",
    "html": "\n      <p class=\"context\">Project HydraFusion · multi-model orchestration in Copilot CLI</p>\n      <h2>Choose HydraFusion.<br>It chooses the <em>model workflow.</em></h2>\n      <div class=\"hydra-composition\">\n        <div class=\"hydra-selection\"><span class=\"editorial-label\">One selection</span><strong>HydraFusion</strong><p>The runtime weighs task capability, quality, cost, and latency.</p><span class=\"hydra-route-label\">Select a workflow &#8594;</span></div>\n        <div class=\"hydra-patterns\">\n          <div class=\"hydra-lane\"><div class=\"hydra-lane-name\"><b>Single</b><span>Direct solution</span></div><div class=\"hydra-path\"><span class=\"model-step\">Selected model</span><i aria-hidden=\"true\">&#8594;</i><span class=\"hydra-result\">Result</span></div></div>\n          <div class=\"hydra-lane\"><div class=\"hydra-lane-name\"><b>Cascade</b><span>Escalate if needed</span></div><div class=\"hydra-path\"><span class=\"model-step\">Efficient draft</span><i aria-hidden=\"true\">&#8594;</i><span class=\"quality-gate\">Quality gate</span><div class=\"cascade-fork\"><span class=\"hydra-result\">Accept result</span><span class=\"model-step arrival\" style=\"--delay:1s\">Or stronger model</span></div></div></div>\n          <div class=\"hydra-lane\"><div class=\"hydra-lane-name\"><b>Critique</b><span>Independent review</span></div><div class=\"hydra-path\"><span class=\"model-step\">Draft</span><i aria-hidden=\"true\">&#8594;</i><span class=\"critic-step\">Read-only critic<small>Different model family</small></span><i aria-hidden=\"true\">&#8594;</i><span class=\"model-step arrival\" style=\"--delay:1.3s\">Revise once</span></div></div>\n        </div>\n      </div>\n      <div class=\"editorial-foot\"><span>From picking a model to selecting how models work together.</span><span>Start with a substantial, well-scoped, single-prompt task.</span></div>\n    ",
    "kicker": ""
  },
  {
    "chapter": "Autonomy building blocks",
    "layout": "editorial hydra-evidence",
    "title": "HydraFusion cut estimated cost in GitHub's offline tests.",
    "html": "\n      <p class=\"context\">GitHub-published evaluation · best tuned HydraFusion configuration</p>\n      <h2>HydraFusion cut estimated cost<br>in <em>GitHub's offline tests.</em></h2>\n      <div class=\"benchmark-composition\">\n        <div class=\"benchmark-baseline\"><span><i></i> Claude Opus 5 cost = 100%</span><span>Quality change in percentage points</span></div>\n        <table class=\"benchmark-chart\">\n          <thead><tr><th>Benchmark</th><th>Estimated workflow cost</th><th>Verified task quality</th></tr></thead>\n          <tbody>\n            <tr><th>TerminalBench 2.1</th><td><div class=\"cost-track\"><span class=\"cost-fill\" style=\"--cost:33;--delay:.1s\"></span></div><span class=\"cost-value\">67% lower</span></td><td><strong class=\"quality-positive\">+4.9</strong><span>points</span></td></tr>\n            <tr><th>DeepSWE</th><td><div class=\"cost-track\"><span class=\"cost-fill\" style=\"--cost:64;--delay:.4s\"></span></div><span class=\"cost-value\">36% lower</span></td><td><strong class=\"quality-negative\">-1.5</strong><span>points</span></td></tr>\n            <tr><th>CheckpointBench</th><td><div class=\"cost-track\"><span class=\"cost-fill\" style=\"--cost:35;--delay:.7s\"></span></div><span class=\"cost-value\">65% lower</span></td><td><strong class=\"quality-negative\">-0.1</strong><span>points</span></td></tr>\n          </tbody>\n        </table>\n        <p class=\"benchmark-reading\">Lower cost in all three tests. Higher verified quality in one, lower in two.</p>\n      </div>\n      <div class=\"editorial-foot\"><span>Same medium reasoning level. Cost includes every invoked workflow leg.</span><span>Controlled evaluations, not a customer savings forecast.</span></div>\n    ",
    "kicker": ""
  },
  {
    "chapter": "Autonomy building blocks",
    "layout": "editorial completion",
    "title": "Advanced Autopilot asks another model whether the task is done.",
    "html": "\n      <p class=\"context\">Advanced Autopilot · completion decisions in VS Code</p>\n      <h2>Advanced Autopilot asks another model<br><em>whether the task is done.</em></h2>\n      <div class=\"completion-composition\">\n        <div class=\"original-request\"><span class=\"editorial-label\">Keep the original request</span><p>\"Add pagination.<br>Preserve existing callers.<br>Add compatibility tests.\"</p></div>\n        <div class=\"completion-loop\">\n          <div class=\"completion-worker\"><span class=\"codicon codicon-hubot\" aria-hidden=\"true\"></span><strong>Main agent</strong><p>Performs a work turn</p></div>\n          <span class=\"decision-connector\" aria-hidden=\"true\">&#8594;</span>\n          <div class=\"completion-check arrival\" style=\"--delay:.5s\"><span class=\"editorial-label\">Separate, small model</span><strong>Request complete?</strong><p>Evaluate after the turn</p></div>\n          <div class=\"completion-return\"><span aria-hidden=\"true\">&#8624;</span><b>Work remains</b><p>Guide the next turn.</p></div>\n          <div class=\"completion-stop arrival\" style=\"--delay:1.1s\"><span class=\"codicon codicon-check\" aria-hidden=\"true\"></span><b>Complete</b><p>Stop.</p></div>\n        </div>\n      </div>\n      <div class=\"editorial-foot\"><span><code>chat.autopilot.advanced.enabled</code></span><span>Completion judgment complements tests and review. It does not replace them.</span></div>\n    ",
    "kicker": ""
  },
  {
    "chapter": "Pull request and review",
    "layout": "editorial handoff",
    "title": "Separate sessions meet at the pull request.",
    "html": "\n      <p class=\"context\">Part 4 · Pull request and review</p>\n      <h2>Separate sessions meet<br>at the <em>pull request.</em></h2>\n      <div class=\"handoff-map\">\n        <div class=\"handoff-origin\">\n          <span class=\"map-index\">01 / SHAPE + BUILD</span>\n          <div class=\"session-fan\"><span>Research</span><span>Implement</span><span>Validate</span></div>\n          <p>Questions, code, test evidence</p>\n          <small>VS Code · GitHub Copilot App<br>Copilot CLI · cloud agent</small>\n        </div>\n        <div class=\"handoff-pr arrival\" style=\"--delay:.6s\">\n          <span class=\"codicon codicon-git-pull-request\" aria-hidden=\"true\"></span>\n          <strong>Pull request</strong><span>Diff + discussion + checks</span>\n          <div class=\"review-orbit\"><span>Code review</span><span>Agent Merge</span></div>\n        </div>\n        <div class=\"handoff-destination\">\n          <span class=\"map-index\">02 / ACCEPT + RELEASE</span>\n          <ol><li>Required checks</li><li>Approval rules</li><li>Merge or merge queue</li><li class=\"deploy-boundary\">Deployment workflow</li></ol>\n          <small>Repository rules · GitHub Actions</small>\n        </div>\n      </div>\n      <div class=\"editorial-foot\"><span>No shared chat transcript required.</span><span>Deployment is a separate workflow.</span></div>\n    ",
    "kicker": ""
  },
  {
    "chapter": "Pull request and review",
    "layout": "editorial merge-repair",
    "title": "Agent Merge can repair blockers, then merge.",
    "html": "\n      <p class=\"context reveal\">Client-driven PR completion</p>\n      <h2 class=\"reveal\">Agent Merge can repair blockers,<br>then merge.</h2>\n      <div class=\"merge-clients reveal\"><span><i class=\"codicon codicon-github\" aria-hidden=\"true\"></i>GitHub Copilot App</span><span><i class=\"codicon codicon-vscode\" aria-hidden=\"true\"></i>VS Code</span><p>Your client starts repair turns. GitHub enforces the merge rules.</p></div>\n      <div class=\"merge-composition reveal\">\n        <div class=\"merge-blockers\">\n          <span class=\"editorial-label\">Choose what it addresses</span>\n          <p><span class=\"codicon codicon-comment-discussion\" aria-hidden=\"true\"></span>Review feedback</p>\n          <p><span class=\"codicon codicon-error\" aria-hidden=\"true\"></span>Failed required checks</p>\n          <p><span class=\"codicon codicon-git-merge\" aria-hidden=\"true\"></span>Conflicts / behind branch</p>\n        </div>\n        <div class=\"merge-cycle\">\n          <div class=\"merge-cycle-row\">\n            <div><b>Inspect PR</b><span>review + CI + branch</span></div>\n            <i aria-hidden=\"true\">→</i>\n            <div class=\"merge-agent\"><b>Agent turn</b><span>repair + push</span></div>\n          </div>\n          <div class=\"merge-return\"><span aria-hidden=\"true\">↖</span> Wait for checks. Inspect the new state.</div>\n          <div class=\"merge-ready\"><span class=\"codicon codicon-pass\" aria-hidden=\"true\"></span>Recheck readiness before merge or queue.</div>\n        </div>\n        <div class=\"merge-policy\">\n          <span class=\"editorial-label\">VS Code merge options</span>\n          <dl>\n            <dt>Off</dt><dd>Repair; leave the PR open.</dd>\n            <dt>If Unchanged</dt><dd>Merge only if no repair was needed.</dd>\n            <dt>When Ready</dt><dd>Merge after checks and approvals pass.</dd>\n          </dl>\n        </div>\n      </div>\n      <div class=\"merge-deployment reveal\">\n        <span>Agent Merge stops at merge or queue.</span>\n        <span class=\"codicon codicon-arrow-right\" aria-hidden=\"true\"></span>\n        <span>Your deployment workflow handles the release.</span>\n      </div>\n      <div class=\"editorial-foot reveal\"><span>Unlike GitHub auto-merge, Agent Merge starts repair turns.</span><span>Repository rules still apply.</span></div>\n    ",
    "kicker": ""
  },
  {
    "chapter": "Pull request and review",
    "layout": "editorial review-effort",
    "title": "Code review offers Lite and Balanced effort.",
    "html": "\n      <p class=\"context reveal\">Copilot code review · Effort levels</p>\n      <h2 class=\"reveal\">Code review offers<br>Lite and Balanced effort.</h2>\n      <div class=\"effort-composition reveal\">\n        <article class=\"effort-option\">\n          <div class=\"effort-name\"><h3>Lite</h3><span>Default</span></div>\n          <p class=\"effort-use\">Fast feedback on routine changes.</p>\n          <p class=\"effort-mechanism\">An ensemble of agents combines its findings into one review.</p>\n          <div class=\"effort-cost\"><strong>$0.05–$1</strong><span>estimated AI-credit consumption per review</span></div>\n        </article>\n        <article class=\"effort-option balanced-option\">\n          <div class=\"effort-name\"><h3>Balanced</h3><span>Higher reasoning</span></div>\n          <p class=\"effort-use\">Complex logic, security-sensitive code, cross-service changes.</p>\n          <p class=\"effort-mechanism\">Routes the PR to a higher-reasoning model for longer analysis.</p>\n          <div class=\"effort-cost\"><strong>$0.25–$5</strong><span>estimated AI-credit consumption per review</span></div>\n        </article>\n      </div>\n      <div class=\"effort-defaults reveal\">\n        <span class=\"editorial-label\">Automatic reviews</span>\n        <span>Organization default</span><i aria-hidden=\"true\">→</i><span>Repository override</span>\n        <small>Or choose the effort when requesting a review.</small>\n      </div>\n      <div class=\"editorial-foot reveal\"><span>USD estimates, not fixed prices. PR size and instructions affect consumption.</span><span>GitHub Actions minutes are additional.</span></div>\n    ",
    "kicker": ""
  },
  {
    "chapter": "Pull request and review",
    "layout": "editorial review-ensemble",
    "title": "Lite code review combines multiple agents.",
    "html": "\n      <p class=\"context reveal\">GitHub experiment · September 11, 2026</p>\n      <h2 class=\"reveal\">Lite code review combines<br>multiple agents.</h2>\n      <div class=\"ensemble-composition reveal\">\n        <div class=\"ensemble-mechanism\">\n          <span class=\"editorial-label\">Independent perspectives</span>\n          <div class=\"ensemble-sheets\" aria-hidden=\"true\"><span></span><span></span><span></span></div>\n          <span class=\"ensemble-arrow\" aria-hidden=\"true\">↓</span>\n          <strong>One combined review</strong>\n          <div class=\"ensemble-cost\"><b>~8%</b><span>lower review cost<br>in the experiment</span></div>\n        </div>\n        <div class=\"ensemble-results\">\n          <p>Increase in average addressed comments per review</p>\n          <div class=\"ensemble-result\"><span>High severity</span><div><i style=\"--gain:47;--delay:.15s\"></i></div><strong>+47%</strong></div>\n          <div class=\"ensemble-result\"><span>Medium</span><div><i style=\"--gain:31;--delay:.35s\"></i></div><strong>+31%</strong></div>\n          <div class=\"ensemble-result\"><span>Low</span><div><i style=\"--gain:11;--delay:.55s\"></i></div><strong>+11%</strong></div>\n          <small>Relative increases, compared with the single-agent approach.</small>\n        </div>\n      </div>\n      <div class=\"editorial-foot reveal\"><span>Source: GitHub's published experiment.</span><span>Addressed comments are not a defect-detection rate.</span></div>\n    ",
    "kicker": ""
  },
  {
    "chapter": "Pull request and review",
    "layout": "editorial review-tools",
    "title": "Code review can test a finding before it comments.",
    "html": "\n      <p class=\"context reveal\">Tool-backed review</p>\n      <h2 class=\"reveal\">Code review can test a finding<br>before it comments.</h2>\n      <div class=\"review-tool-composition reveal\">\n        <div class=\"review-hypothesis\">\n          <span class=\"editorial-label\">Illustrative review</span>\n          <h3>Does an expired cursor<br>retry forever?</h3>\n          <pre><code>if (!response.ok) {\n  return retry(cursor);\n}</code></pre>\n          <p>A suspicious diff is the starting point.</p>\n        </div>\n        <div class=\"review-validation\">\n          <div class=\"review-runner\">\n            <span class=\"editorial-label\">Actions runner · agent firewall</span>\n            <strong>Build · test · targeted script</strong>\n            <div class=\"review-test-result\"><span class=\"codicon codicon-error\" aria-hidden=\"true\"></span><code>expired_cursor_stops_retrying</code><b>FAIL</b></div>\n            <p>Available shell tools can validate the hypothesis.</p>\n          </div>\n          <div class=\"review-evidence-arrow\" aria-hidden=\"true\">↓</div>\n          <div class=\"review-finding\"><span class=\"editorial-label\">Finding with evidence</span><p>The 410 response enters the retry path. The targeted test never reaches an exit.</p></div>\n        </div>\n      </div>\n      <div class=\"review-followup reveal\"><b>After a fix, rereview tracks</b><span>Open</span><span>Resolved since last review</span><span>Previously missed</span></div>\n      <div class=\"editorial-foot reveal\"><span>Tests are available, not guaranteed on every review.</span><span>Request rereview, or configure it on each push.</span></div>\n    ",
    "kicker": ""
  },
  {
    "chapter": "Pull request and review",
    "layout": "editorial review-context",
    "title": "Code review can use your skills and MCP context.",
    "html": "\n      <p class=\"context reveal\">Repository skills + MCP context</p>\n      <h2 class=\"reveal\">Code review can use your skills<br>and MCP context.</h2>\n      <div class=\"review-context-composition reveal\">\n        <div class=\"review-context-inputs\">\n          <article><span class=\"editorial-label\">Skill · review-api-contracts</span><p>Compare error handling with the service contract. Check retry and recovery paths.</p><small>Ordinary repository Agent Skill</small></article>\n          <article><span class=\"editorial-label\">PR description + instructions</span><p>“Implements API-421. Consult the linked service contract when reviewing.”</p><small>Identifiers help the reviewer find relevant context.</small></article>\n          <article class=\"mcp-contract\"><span class=\"editorial-label\">Configured MCP server</span><p>API-421 links to the contract. “Expired cursors return 410. Start a fresh query.”</p><small>Issue tracker / internal documentation</small></article>\n        </div>\n        <div class=\"review-context-output\">\n          <span class=\"codicon codicon-comment-discussion\" aria-hidden=\"true\"></span>\n          <span class=\"editorial-label\">Illustrative finding</span>\n          <h3>This retry violates<br>the service contract.</h3>\n          <p>Restart pagination on 410 instead of retrying the expired cursor.</p>\n          <div class=\"review-context-basis\"><span>code</span><span>team procedure</span><span>service context</span></div>\n        </div>\n      </div>\n      <div class=\"editorial-foot reveal\"><span>Skills and instructions come from the PR's head branch.</span><span>Repository MCP settings serve both cloud agent and code review.</span></div>\n    ",
    "kicker": ""
  },
  {
    "chapter": "Pull request and review",
    "layout": "editorial review-authority",
    "title": "Code review approvals count only if you enable them.",
    "html": "\n      <p class=\"context reveal\">Approval authority · Opt-in</p>\n      <h2 class=\"reveal\">Code review approvals count<br>only if you enable them.</h2>\n      <div class=\"approval-composition reveal\">\n        <div class=\"approval-default\">\n          <span class=\"editorial-label\">Default</span>\n          <strong>An assessment</strong>\n          <p>The overview says whether Copilot considers the PR ready to approve.</p>\n          <div class=\"approval-rule\"><span class=\"codicon codicon-circle-slash\" aria-hidden=\"true\"></span>Does not satisfy required approvals.</div>\n        </div>\n        <div class=\"approval-enabled\">\n          <span class=\"editorial-label\">Explicitly enabled by policy</span>\n          <strong>An approving review</strong>\n          <p>Copilot can submit an approval that counts toward the repository's rule.</p>\n          <div class=\"approval-policy-chain\"><span>Enterprise</span><i aria-hidden=\"true\">→</i><span>Organization</span><i aria-hidden=\"true\">→</i><span>Repository</span></div>\n        </div>\n      </div>\n      <div class=\"approval-freshness reveal\"><span class=\"codicon codicon-git-commit\" aria-hidden=\"true\"></span><b>New commit</b><span aria-hidden=\"true\">→</span><span>Approval dismissed</span><span aria-hidden=\"true\">→</span><span>Request another review</span></div>\n      <div class=\"editorial-foot reveal\"><span>An approving review does not bypass other repository rules.</span><span>Agent Merge still waits for the required checks and approvals.</span></div>\n    ",
    "kicker": ""
  },
  {
    "chapter": "Recurring work",
    "layout": "section",
    "title": "Automations repeat work. Agentic Workflows live in Git.",
    "html": "\n      <div class=\"transition-statement\">\n        <div class=\"divider-line reveal\"></div>\n        <p class=\"context reveal\">Part 5 · Recurring work</p>\n        <h2 class=\"reveal\">Automations repeat work.<br>Agentic Workflows live in Git.</h2>\n      </div>\n    ",
    "kicker": ""
  },
  {
    "chapter": "Recurring work",
    "layout": "editorial recurring",
    "title": "VS Code Automations save the task and the session configuration.",
    "html": "\n      <p class=\"context reveal\">VS Code · Automations</p>\n      <h2 class=\"reveal\">VS Code Automations save the task.<br><em>Repeat the session.</em></h2>\n      <div class=\"automation-recipe\">\n        <div class=\"task-spec reveal\">\n          <span class=\"editorial-label\">Example prompt</span>\n          <p>Summarize the last 24 hours of commits.<br>Link the changes. Flag documentation gaps.<br><strong>Do not modify files.</strong></p>\n          <dl class=\"compact-facts\">\n            <dt>Workspace</dt><dd>The repository to inspect</dd>\n            <dt>Session</dt><dd>Agent, model, permissions, isolation</dd>\n            <dt>Schedule</dt><dd>Manual · hourly · daily · weekly</dd>\n          </dl>\n        </div>\n        <div class=\"run-sequence reveal\">\n          <span class=\"editorial-label\">One saved definition</span>\n          <div class=\"run-entry\"><b>Run now</b><span>Inspect the first session</span></div>\n          <div class=\"run-entry\"><b>Enable schedule</b><span>Start future sessions automatically</span></div>\n          <div class=\"run-entry\"><b>History</b><span>Read results, changes, and approval requests</span></div>\n        </div>\n      </div>\n      <div class=\"editorial-foot reveal\"><span>One active session per Automation.</span><span>A schedule does not bypass permissions.</span></div>\n    ",
    "kicker": ""
  },
  {
    "chapter": "Recurring work",
    "layout": "editorial recurring",
    "title": "Remote Automations keep the schedule on the Agent Host.",
    "html": "\n      <p class=\"context reveal\">VS Code · Remote Agent Host</p>\n      <h2 class=\"reveal\">Remote Automations keep the<br><em>schedule on the Agent Host.</em></h2>\n      <div class=\"remote-schedule reveal\">\n        <div class=\"schedule-client\">\n          <span class=\"codicon codicon-device-laptop\" aria-hidden=\"true\"></span>\n          <h3>Your laptop</h3>\n          <p>Configure the task.<br>Reconnect to inspect results.</p>\n        </div>\n        <div class=\"schedule-link\"><span>SSH / Dev Tunnel</span><i aria-hidden=\"true\"></i><small>The client can disconnect</small></div>\n        <div class=\"schedule-host\">\n          <span class=\"editorial-label\">Your DevBox · stays awake</span>\n          <h3>Agent Host</h3>\n          <ol class=\"host-steps\"><li><b>Schedule</b><span>Host admits the next run</span></li><li><b>Session</b><span>Remote workspace and toolchain</span></li><li><b>History</b><span>Host retains the run record</span></li></ol>\n        </div>\n      </div>\n      <div class=\"editorial-foot reveal\"><span>The host process must remain running.</span><span>Unattended work needs tools and credentials available on the host.</span></div>\n    ",
    "kicker": ""
  },
  {
    "chapter": "Recurring work",
    "layout": "editorial recurring",
    "title": "Cloud Automations run without your laptop or DevBox.",
    "html": "\n      <p class=\"context reveal\">GitHub Copilot App + GitHub.com</p>\n      <h2 class=\"reveal\">Cloud Automations run without<br><em>your laptop or DevBox.</em></h2>\n      <div class=\"cloud-automation reveal\">\n        <div class=\"cloud-inputs\">\n          <span class=\"editorial-label\">Configure once</span>\n          <dl class=\"compact-facts\">\n            <dt>Trigger</dt><dd>Schedule, new issue, PR opened or updated</dd>\n            <dt>Task</dt><dd>Prompt, model, repository</dd>\n            <dt>Authority</dt><dd>Only the tools this task needs</dd>\n          </dl>\n        </div>\n        <div class=\"cloud-execution\">\n          <span class=\"editorial-label\">GitHub-hosted execution</span>\n          <h3>Copilot cloud agent</h3>\n          <p>Runs inside one repository's scope.</p>\n          <div class=\"output-types\"><span>Issue labels</span><span>Pull request</span><span>Session log</span></div>\n          <small>Output depends on the task and selected tools.</small>\n        </div>\n      </div>\n      <div class=\"visibility-strip reveal\"><div><b>Definition</b><span>Private to its creator; outside Git</span></div><div><b>Result sessions</b><span>Visible to repository readers</span></div></div>\n    ",
    "kicker": ""
  },
  {
    "chapter": "Recurring work",
    "layout": "editorial recurring",
    "title": "Agentic Workflows put the task and its limits in Git.",
    "html": "\n      <p class=\"context reveal\">Agentic Workflows · AgentRC Issue Triage</p>\n      <h2 class=\"reveal\">Agentic Workflows put the task<br>and its limits <em>in Git.</em></h2>\n      <div class=\"workflow-source reveal\">\n        <div class=\"source-excerpt\">\n          <span class=\"editorial-label\">issue-triage.md · excerpt</span>\n          <pre><code><span class=\"code-key\">on:</span>\n  issues:\n    types: [opened, reopened]\n<span class=\"code-key\">max-ai-credits:</span> 100\n<span class=\"code-key\">max-daily-ai-credits:</span> 750\n<span class=\"code-key\">max-turns:</span> 15</code></pre>\n          <p>Markdown below the configuration defines<br>completeness checks, duplicates, and next steps.</p>\n        </div>\n        <ol class=\"source-path\">\n          <li><b>Markdown source</b><span>Review the task and constraints in a PR</span></li>\n          <li><b>Compiled lock workflow</b><span>Commit the generated Actions definition</span></li>\n          <li><b>Actions run</b><span>Inspect execution and bounded outputs</span></li>\n        </ol>\n      </div>\n      <div class=\"editorial-foot reveal\"><span>Actual AgentRC configuration. This workflow makes no code changes.</span><span>Repository maintainers review changes to the automation itself.</span></div>\n    ",
    "kicker": ""
  },
  {
    "chapter": "Recurring work",
    "layout": "editorial recurring",
    "title": "Agentic Workflows let the agent request writes, not hold the write token.",
    "html": "\n      <p class=\"context reveal\">Agentic Workflows · Safe outputs</p>\n      <h2 class=\"reveal\">The agent requests a write.<br><em>A separate job applies it.</em></h2>\n      <div class=\"safe-output-path reveal\">\n        <div class=\"reasoning-job\"><span class=\"editorial-label\">Agent job</span><h3>Read the issue.<br>Decide what it needs.</h3><p>Repository read access.<br>No repository write token.</p></div>\n        <div class=\"write-request\"><span class=\"editorial-label\">Structured request</span><div><b>bug</b><b>vscode-extension</b></div><p>Propose labels and<br>a maintainer-facing comment</p><small>Illustrative request</small></div>\n        <div class=\"write-job\"><span class=\"editorial-label\">Safe-output job</span><h3>Validate.<br>Apply allowed changes.</h3><p>Separate, narrow<br>repository write permissions.</p></div>\n      </div>\n      <div class=\"output-limits reveal\"><span>Actual triage limits</span><div><strong>2</strong> allowlisted labels</div><div><strong>1</strong> issue type</div><div><strong>1</strong> comment</div></div>\n      <div class=\"editorial-foot reveal\"><span>Limits come from the workflow, not the agent's promise.</span><span>No justified action? Request a noop.</span></div>\n    ",
    "kicker": ""
  },
  {
    "chapter": "Recurring work",
    "layout": "editorial recurring",
    "title": "Choose where an Automation runs and how its definition is reviewed.",
    "html": "\n      <p class=\"context reveal\">Automations or Agentic Workflows</p>\n      <h2 class=\"reveal\">Choose where it runs.<br>Choose <em>how changes are reviewed.</em></h2>\n      <div class=\"runtime-choices reveal\">\n        <article><div><h3>VS Code Automation</h3><span>Use your workspace and toolchain</span></div><p>Local or remote Agent Host.<br>Saved session configuration and History.</p><b>You keep the host available.</b></article>\n        <article><div><h3>Cloud Automation</h3><span>Configure a hosted task in a form</span></div><p>GitHub-hosted, repository-scoped.<br>Creator-private definition outside Git.</p><b>Select the tools it can use.</b></article>\n        <article><div><h3>Agentic Workflow</h3><span>Maintain the automation with the repository</span></div><p>Versioned Markdown and compiled lock.<br>Actions runs and validated outputs.</p><b>Review definition changes in PRs.</b></article>\n      </div>\n      <div class=\"editorial-foot reveal\"><span>Schedules and events overlap. They are not the deciding difference.</span><span>The Copilot App also supports local Automations.</span></div>\n    ",
    "kicker": ""
  },
  {
    "chapter": "Engineering systems",
    "layout": "section",
    "title": "Agent Plugins ship team practices.",
    "html": "\n      <div class=\"transition-statement\">\n        <div class=\"divider-line reveal\"></div>\n        <p class=\"context reveal\">Part 6 · Team capability</p>\n        <h2 class=\"reveal\">Agent Plugins ship team practices.</h2>\n      </div>\n    ",
    "kicker": ""
  },
  {
    "chapter": "Engineering systems",
    "layout": "editorial customization",
    "title": "Skills carry procedures. Agent Plugins package the pieces.",
    "html": "\n      <p class=\"context reveal\">Agent customizations · Jobs, not file formats</p>\n      <h2 class=\"reveal\">Skills carry procedures.<br><em>Plugins package the pieces.</em></h2>\n      <div class=\"customization-map reveal\">\n        <div class=\"standing-rule\"><span class=\"editorial-label\">Repository context</span><h3>Instructions</h3><p>Standing rules.<br>Build commands.<br>Project conventions.</p></div>\n        <div class=\"plugin-bracket\">\n          <span class=\"editorial-label\">Agent Plugin · related capabilities, one package</span>\n          <div class=\"customization-roles\">\n            <div><h3>Skills</h3><p>Procedures, scripts,<br>and references on demand</p></div>\n            <div><h3>Custom agents</h3><p>A named role with<br>selected tools and model</p></div>\n            <div><h3>MCP servers</h3><p>Tools and data<br>from other systems</p></div>\n            <div><h3>Hooks</h3><p>Code that runs<br>at lifecycle events</p></div>\n          </div>\n        </div>\n      </div>\n      <div class=\"editorial-foot reveal\"><span>Use a skill for a reusable procedure. It can also be invoked explicitly.</span><span>A plugin is a package, not another agent.</span></div>\n    ",
    "kicker": ""
  },
  {
    "chapter": "Engineering systems",
    "layout": "editorial customization",
    "title": "Agent Plugins have a portable core and client-specific extensions.",
    "html": "\n      <p class=\"context reveal\">Agent Plugins 1.0</p>\n      <h2 class=\"reveal\">Agent Plugins have a portable core<br>and <em>client-specific extensions.</em></h2>\n      <div class=\"package-cutaway reveal\">\n        <div class=\"package-files\">\n          <span class=\"editorial-label\">Illustrative Agent Plugins 1.0 package</span>\n          <div class=\"package-file manifest-file\"><code>plugin.json</code><span>Identity, version, schema</span></div>\n          <div class=\"package-file portable-file\"><code>skills/</code><span>Procedures + resources</span></div>\n          <div class=\"package-file portable-file\"><code>mcp.json</code><span>Server definitions</span></div>\n          <div class=\"package-file client-file\"><code>com.github.copilot/</code><span>Agents, hooks, rules</span></div>\n          <div class=\"package-file client-file\"><code>automations/</code><span>VS Code root-folder convention</span></div>\n        </div>\n        <div class=\"package-meaning\">\n          <div><span class=\"editorial-label green\">Portable core</span><p>Skills and MCP configuration<br>travel across supporting clients.</p></div>\n          <div><span class=\"editorial-label violet\">Client extensions</span><p>Additional behavior is used<br>only by clients that support it.</p></div>\n          <div><span class=\"editorial-label amber\">Still your decision</span><p>Publisher trust, credentials,<br>tool permissions, and containment.</p></div>\n          </div>\n      </div>\n      <div class=\"editorial-foot reveal\"><span>Portable packaging does not make security policy portable.</span><span>An Automation template does not enable a schedule on install.</span></div>\n    ",
    "kicker": ""
  },
  {
    "chapter": "Engineering systems",
    "layout": "editorial customization",
    "title": "Use plugin marketplaces to roll out tested team practices.",
    "html": "\n      <p class=\"context reveal\">Agent Plugins · Marketplace distribution</p>\n      <h2 class=\"reveal\">Use plugin marketplaces to<br><em>roll out tested team practices.</em></h2>\n      <div class=\"marketplace-governance reveal\"><b>Enterprise governance</b><span>Approved catalogs</span><span>Required plugins</span><span>Update policy</span></div>\n      <div class=\"marketplace-rollout reveal\">\n        <div class=\"release-source\"><span class=\"editorial-label\">Team-owned repositories</span><h3>Maintain the plugins.</h3><p>Review changes.<br>Run evals.<br>Version releases.</p></div>\n        <div class=\"catalog-source\"><span class=\"editorial-label\">Shared marketplace</span><h3>Distribute the plugins.</h3><p>One catalog teams<br>can adopt and maintain.</p><code>marketplace.json</code></div>\n        <div class=\"rollout-destinations\"><div><span class=\"editorial-label\">Developer clients</span><p>VS Code · Copilot CLI<br>GitHub Copilot App</p></div><div><span class=\"editorial-label\">Project repositories</span><p>Recommend the shared plugins<br>instead of copying their contents.</p></div></div>\n      </div>\n      <div class=\"editorial-foot reveal\"><span>Invest in ownership, evals, and releases alongside distribution.</span><span>Client capability support still differs.</span></div>\n    ",
    "kicker": ""
  },
  {
    "chapter": "Engineering systems",
    "layout": "editorial customization",
    "title": "Plugin evals test when a skill should run, and when it should not.",
    "html": "\n      <p class=\"context reveal\">Team Kit · Vally evals · review-areas</p>\n      <h2 class=\"reveal\">Plugin evals test when a skill<br><em>should run, and should not.</em></h2>\n      <div class=\"eval-cases reveal\">\n        <div class=\"eval-case\"><span class=\"editorial-label\">Positive case · Expected activation</span><p>“Review my code for<br>correctness and security”</p><div><code>review-areas</code><b>Required</b></div></div>\n        <div class=\"eval-case negative-case\"><span class=\"editorial-label\">Negative case · Expected non-activation</span><p>“Plan a new implementation<br>for the cache layer…”</p><div><code>review-areas</code><b>Disallowed</b></div></div>\n      </div>\n      <div class=\"eval-ci reveal\"><div><b>Validate specs</b><span>Invalid definitions fail CI</span></div><div><b>Run model cases</b><span>Inspect activation, output, and tool use</span></div><div><b>Publish results</b><span>Grader failures inform improvement</span></div></div>\n      <div class=\"editorial-foot reveal\"><span>These are test expectations from the spec, not measured pass rates.</span><span>Execution errors still fail CI.</span></div>\n    ",
    "kicker": ""
  },
  {
    "chapter": "Engineering systems",
    "layout": "editorial customization",
    "title": "Managed settings control plugin sources, enablement, and updates.",
    "html": "\n      <p class=\"context reveal\">Enterprise-managed settings · Plugin rollout</p>\n      <h2 class=\"reveal\">Managed settings control plugin<br><em>sources, enablement, and updates.</em></h2>\n      <div class=\"managed-example reveal\">\n        <div class=\"policy-json\">\n          <span class=\"editorial-label\">Illustrative enterprise policy</span>\n          <pre><code>{\n  <span class=\"code-key\">\"extraKnownMarketplaces\"</span>: {\n    \"engineering\": {\n      \"source\": {\n        \"source\": \"github\",\n        \"repo\": \"contoso/agent-plugins\"\n      },\n      <span class=\"code-key\">\"autoUpdate\"</span>: true\n    }\n  },\n  <span class=\"code-key\">\"enabledPlugins\"</span>: {\n    \"review-api@engineering\": true\n  }\n}</code></pre>\n        </div>\n        <div class=\"policy-explanation\"><div><h3>Register the catalog.</h3><p>The source repository supplies<br>the engineering marketplace.</p></div><div><h3>Keep plugins current.</h3><p>Require automatic updates<br>from this marketplace.</p></div><div><h3>Require the review plugin.</h3><p>Enable <code>review-api</code> from<br>the named marketplace.</p></div></div>\n      </div>\n      <div class=\"editorial-foot reveal\"><span>Server-managed file: <code>.github-private/copilot/managed-settings.json</code></span><span>Add <code>strictKnownMarketplaces</code> to restrict installation sources.</span></div>\n    ",
    "kicker": ""
  },
  {
    "chapter": "Engineering systems",
    "layout": "editorial customization",
    "title": "Plugin marketplaces can ship MCP tools with the skills that use them.",
    "html": "\n      <p class=\"context reveal\">MCP · Distribution through Agent Plugins</p>\n      <h2 class=\"reveal\">Plugin marketplaces can ship MCP tools<br><em>with the skills that use them.</em></h2>\n      <div class=\"mcp-packaging reveal\">\n        <div class=\"mcp-marketplace\"><span class=\"editorial-label\">Plugin marketplace</span>\n          <div class=\"mcp-plugin\"><h3>Incident-response plugin</h3><span class=\"editorial-label\">Illustrative package</span>\n            <div class=\"mcp-bundle-part\"><code>skills/triage/SKILL.md</code><p>How to investigate an incident<br>and verify the proposed fix.</p></div>\n            <div class=\"mcp-bundle-part\"><code>mcp.json</code><p>Server configuration for<br>incident and service context.</p></div>\n          </div>\n        </div>\n        <div class=\"mcp-registry\"><span class=\"editorial-label\">MCP registry</span><h3>Find and configure<br>MCP servers.</h3><p>A server catalog does not package<br>the surrounding agent procedure.</p><p>Plugins can bundle that procedure<br>with tools, agents, and hooks.</p></div>\n      </div>\n      <div class=\"editorial-foot reveal\"><span>One plugin release can update the procedure and its tool configuration together.</span><span>Credentials and service permissions remain separate.</span></div>\n    ",
    "kicker": ""
  },
  {
    "chapter": "Runtime systems",
    "layout": "section",
    "title": "Agent Factories make multi-agent runs repeatable.",
    "html": "\n      <div class=\"transition-statement\">\n        <div class=\"divider-line reveal\"></div>\n        <p class=\"context reveal\">Part 7 · Runtime systems · Experimental</p>\n        <h2 class=\"reveal\">Agent Factories make<br>multi-agent runs repeatable.</h2>\n      </div>\n    ",
    "kicker": ""
  },
  {
    "chapter": "Runtime systems",
    "layout": "editorial factory-pattern",
    "title": "Agent Factories defines how workers run and combine results.",
    "html": "\n      <p class=\"context reveal\">Copilot SDK · Experimental Node.js API</p>\n      <h2 class=\"reveal\">Agent Factories defines how workers<br><em>run and combine results.</em></h2>\n      <div class=\"factory-review-map reveal\">\n        <div class=\"factory-definition\"><span class=\"editorial-label\">Register once in the session</span><h3>review-changed</h3><p>Changed files in.<br>Verified findings out.</p><code>defineFactory({ meta, run })</code></div>\n        <div class=\"factory-pipeline\"><span class=\"editorial-label\">Illustrative review workflow</span>\n          <div class=\"factory-lane-labels\"><span>Review each file</span><span>Verify its findings</span></div>\n          <div class=\"factory-lane\"><b>API file</b><span>Review agent</span><span>Verifier agent</span></div>\n          <div class=\"factory-lane\"><b>Test file</b><span>Review agent</span><span>Verifier agent</span></div>\n          <p class=\"factory-pipeline-note\"><code>ctx.pipeline()</code> lets each file advance independently.</p>\n          <div class=\"factory-report\"><span class=\"codicon codicon-file-text\" aria-hidden=\"true\"></span><b>Combine verified findings</b><span>Return the report after the pipeline settles.</span></div>\n        </div>\n      </div>\n      <div class=\"factory-runtime-strip reveal\"><b>The run owns</b><span>Worker lifecycle</span><span>Progress + usage</span><span>Configured limits</span><span>Saved results</span></div>\n      <div class=\"editorial-foot reveal\"><span>Author code controls sequencing. Agents perform the scoped tasks.</span><span>Partial failures must be handled in the workflow.</span></div>\n    ",
    "kicker": ""
  },
  {
    "chapter": "Runtime systems",
    "layout": "editorial factory-controls",
    "title": "Copilot CLI lets you inspect, pause, and resume Factory runs.",
    "html": "\n      <p class=\"context reveal\">Copilot CLI · Operator controls</p>\n      <h2 class=\"reveal\">Copilot CLI lets you inspect, pause,<br>and resume <em>Factory runs.</em></h2>\n      <div class=\"factory-inspection reveal\">\n        <div class=\"factory-command\"><span class=\"editorial-label\">In the owning session</span><code>/factories</code><p>Open active, paused,<br>and recent runs.</p><small>Requires Factory access in the current build.</small></div>\n        <div class=\"factory-inspect-path\"><span class=\"editorial-label\">Inspection path · not a product screenshot</span><div><b>Run</b><span>Status, usage, outcome</span></div><div><b>Phase</b><span>Progress and its agents</span></div><div><b>Agent</b><span>Timeline when available</span></div></div>\n      </div>\n      <div class=\"factory-key-actions reveal\"><div><kbd>P</kbd><b>Pause</b><span>Stop an active attempt;<br>keep the run resumable.</span></div><div><kbd>X</kbd><b>Stop</b><span>Cancel work on<br>the selected active run.</span></div><div><kbd>R</kbd><b>Resume</b><span>Start another attempt<br>on a resumable run.</span></div></div>\n      <div class=\"editorial-foot reveal\"><span>Available actions follow the selected run's state.</span><span>CLI shortcuts shown here, not deck shortcuts.</span></div>\n    ",
    "kicker": ""
  },
  {
    "chapter": "Runtime systems",
    "layout": "editorial factory-resume",
    "title": "Agent Factories resumes by reusing saved results.",
    "html": "\n      <p class=\"context reveal\">Same run ID · Another attempt</p>\n      <h2 class=\"reveal\">Agent Factories resumes<br>by <em>reusing saved results.</em></h2>\n      <div class=\"factory-replay-map reveal\">\n        <div class=\"replay-columns\"><span></span><span>Inventory</span><span>Review</span><span>Report</span></div>\n        <div class=\"replay-attempt\"><b>Attempt 1</b><div class=\"replay-saved\">Result saved</div><div class=\"replay-interrupted\">Interrupted</div><div class=\"replay-pending\">Not reached</div></div>\n        <div class=\"replay-journal\"><b>Journal</b><div><code>inventory-v1</code><span>Stored JSON result</span></div><p>No saved review result yet.</p></div>\n        <div class=\"replay-attempt replay-second\"><b>Resume</b><div class=\"replay-reused\">Reuse result</div><div>Run again</div><div>Continue</div></div>\n      </div>\n      <div class=\"factory-repeat-warning reveal\"><b>External writes can repeat.</b><span>A crash after creating an issue but before saving the result can create a duplicate on retry.</span></div>\n      <div class=\"editorial-foot reveal\"><span>Use stable, versioned keys and idempotent writes.</span><span>Resume keeps prior resource consumption.</span></div>\n    ",
    "kicker": ""
  },
  {
    "chapter": "Close",
    "layout": "editorial workflow-close",
    "title": "From a question to a reviewed pull request.",
    "html": "\n      <p class=\"context reveal\">Return to the work item</p>\n      <h2 class=\"reveal\">From a question<br>to a <em>reviewed pull request.</em></h2>\n      <div class=\"closing-workflow reveal\">\n        <div><span class=\"codicon codicon-comment-discussion\" aria-hidden=\"true\"></span><h3>Plan together.</h3><p>Research, questions,<br>and feedback on the plan.</p></div>\n        <div><span class=\"codicon codicon-git-branch\" aria-hidden=\"true\"></span><h3>Split the work.</h3><p>Independent sessions.<br>Explicit ownership and isolation.</p></div>\n        <div><span class=\"codicon codicon-git-pull-request\" aria-hidden=\"true\"></span><h3>Review and merge.</h3><p>Diffs, tests, code review,<br>and repository rules.</p></div>\n      </div>\n      <div class=\"closing-repeat reveal\"><span class=\"codicon codicon-sync\" aria-hidden=\"true\"></span><div><h3>Package and repeat what worked.</h3><p>Skills and plugins carry the practice. Evals test it.<br>Automations and Agentic Workflows run recurring tasks. Factories coordinate repeatable multi-agent runs.</p></div></div>\n      <div class=\"editorial-foot reveal\"><span>You set the scope, answer the hard questions, and decide what is ready.</span><span>One workflow, not one required product stack.</span></div>\n    ",
    "kicker": ""
  }
];
